# Generated by Django 4.2 on 2023-06-16 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=100)),
                ('img', models.ImageField(default=None, upload_to='pics')),
                ('desc', models.TextField(default=None)),
                ('price', models.IntegerField(default=None)),
                ('offer', models.BooleanField(default=False)),
            ],
        ),
    ]
